"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$directory$package$git_branch$git_status$git_state
\$ '''

[directory]
truncate_to_repo = true

[username]
show_always = true
format = '[$user]($style)'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_only = false

[sudo]
disabled = false
format = '[$symbol]($style)'

[python]
disabled = false
